spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tb_springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver